version: "3.9"

services:
  website:
    container_name: insecure
    build: ./
    networks:
      insecure-net:
        ipv4_address: 172.10.0.2

networks:
  insecure-net:
    ipam:
      driver: default
      config:
        - subnet: "172.10.0.0/24"
